Repository DUNE-DAQ/tpgtools, pull requests merged in 2024-02, with the labels that each got.

#6 Add python tools to develop
  .gitignore
  docs/README.md
  python/cluster_maker.py
  python/hdf5_converter.py
  python/image_creator.py
  python/properties_plotter.py
  python/utils.py
  scripts/.gitignore
  scripts/create_images.py
  scripts/plot_tp_properties.py
  scripts/plot_trigprim_output_data.py
Labels: enhancement, miscellaneous deliverable

#11 Fixed name of fdreadoutlibs/wibeth/tpg/ProcessAbsRSAVX2.hpp in TPGEmulator.cpp
  src/TPGEmulator.cpp
Labels: miscellaneous deliverable

#18 Adding proper TP algorithm names
  apps/wib2_tpg_algorithms_emulator.cxx
  include/tpgtools/TPGEmulator.hpp
  src/TPGEmulator.cpp
Labels: maintenance, miscellaneous deliverable
